apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: kasten-profiles
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kasten-io
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/MichaelHaigh/kasten-automation.git
    targetRevision: argocd-setup
    path: argocd/addons/kasten-profiles
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
