apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: kasten-io
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kasten-io
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://charts.kasten.io/
      targetRevision: 8.0.14
      chart: k10
      helm:
        releaseName: k10
        valuesObject:
          auth:
            tokenAuth:
              enabled: true
          externalGateway:
            create: true
          secrets:
            googleClientSecretName: google-storageadmin-sa
    - repoURL: https://github.com/MichaelHaigh/kasten-automation.git
      targetRevision: argocd-setup # change to main when merging to main
      path: argocd/kasten-policies/kasten
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
