config:
  spec:
    destination:
      server: https://kubernetes.default.svc

applications:
  - name: kasten-io
    chart: k10
    tool:
      helm:
        releaseName: k10
        valuesObject:
          auth:
            tokenAuth:
              enabled: true
          externalGateway:
            create: true
    source:
      repoURL: https://charts.kasten.io/
      targetRevision: 8.0.14
  - name: pacman
    chart: pacman
    tool:
      helm:
        releaseName: pacman
        valuesObject:
          service:
            type: LoadBalancer
    source:
      repoURL: https://michaelhaigh.github.io/pacman/
      targetRevision: 0.1.23
